[package]
name = "yamlrs"
version = "0.1.0"
edition = "2024"

[lib]
name = "yamlrs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.172"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
